//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace SAML2.Properties {
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    [GeneratedCode("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public sealed class Saml20Resources {
        
        private static ResourceManager _resourceManager;
        
        private static CultureInfo _resourceCulture;
        
        private Saml20Resources() {
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(_resourceManager, null)) {
                    ResourceManager temp = new ResourceManager("SAML2.Properties.Saml20Resources", typeof(Saml20Resources).Assembly);
                    _resourceManager = temp;
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Action SAMLRequest requires you to set the Request property.'.
        /// </summary>
        public static string ActionRequestMismatch {
            get {
                return ResourceManager.GetString("ActionRequestMismatch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Action SAMLResponse requires you to set the Response property.'.
        /// </summary>
        public static string ActionResponseMismatch {
            get {
                return ResourceManager.GetString("ActionResponseMismatch", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The IdentityProviderEndpointElement with id &quot;{0}&quot; was not found in configuration file.'.
        /// </summary>
        public static string InvalidIdpEndPointId {
            get {
                return ResourceManager.GetString("InvalidIdpEndPointId", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;IdentityProviderEndpointElements&gt; element under &lt;Safewhere.SAML20Federation&gt; in configuration file.'.
        /// </summary>
        public static string MissingIDPEndpoints {
            get {
                return ResourceManager.GetString("MissingIDPEndpoints", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'The &quot;metadata&quot; attribute on the &lt;IdentityProviderEndpointElements&gt; tag must contain the path to a directory holding metadata descriptions of your federation partners.'.
        /// </summary>
        public static string MissingMetadataLocation {
            get {
                return ResourceManager.GetString("MissingMetadataLocation", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;Safewhere.SAML20Federation&gt; element in configuration file.'.
        /// </summary>
        public static string MissingSaml20Federation {
            get {
                return ResourceManager.GetString("MissingSaml20Federation", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;ServiceProvider&gt; element under &lt;Safewhere.SAML20Federation&gt; element in configuration file.'.
        /// </summary>
        public static string MissingServiceProvider {
            get {
                return ResourceManager.GetString("MissingServiceProvider", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing id attribute on the &lt;ServiceProvider&gt; element in configuration file.'.
        /// </summary>
        public static string MissingServiceProviderId {
            get {
                return ResourceManager.GetString("MissingServiceProviderId", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;SigningCertificate&gt; element under &lt;ServiceProvider&gt; element in configuration file.'.
        /// </summary>
        public static string MissingSigningCertificate {
            get {
                return ResourceManager.GetString("MissingSigningCertificate", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;SLO&gt; element or missing attribute under &lt;IdentityProviderEndpointElements&gt; in configuration file.'.
        /// </summary>
        public static string MissingSLO {
            get {
                return ResourceManager.GetString("MissingSLO", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing &lt;SSO&gt; element or missing attribute under &lt;IdentityProviderEndpointElements&gt; in configuration file.'.
        /// </summary>
        public static string MissingSSO {
            get {
                return ResourceManager.GetString("MissingSSO", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Unable to load the certificate specified in &lt;SigningCertificate&gt; element in configuration file.'.
        /// </summary>
        public static string SigningCertficateLoadError {
            get {
                return ResourceManager.GetString("SigningCertficateLoadError", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Missing access to private key for signing certificate.'.
        /// </summary>
        public static string SigningCertificateMissingPrivateKey {
            get {
                return ResourceManager.GetString("SigningCertificateMissingPrivateKey", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Type of request (&quot;{0}&quot;) is not supported.'.
        /// </summary>
        public static string UnsupportedRequestType {
            get {
                return ResourceManager.GetString("UnsupportedRequestType", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Type of response (&quot;{0}&quot;) is not supported.'.
        /// </summary>
        public static string UnsupportedResponseType {
            get {
                return ResourceManager.GetString("UnsupportedResponseType", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'The IdentityProviderEndpointElement with id &quot;{0}&quot; was not found in configuration file.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string InvalidIdpEndPointIdFormat(object arg0) {
            return string.Format(_resourceCulture, InvalidIdpEndPointId, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Type of request (&quot;{0}&quot;) is not supported.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UnsupportedRequestTypeFormat(object arg0) {
            return string.Format(_resourceCulture, UnsupportedRequestType, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Type of response (&quot;{0}&quot;) is not supported.'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UnsupportedResponseTypeFormat(object arg0) {
            return string.Format(_resourceCulture, UnsupportedResponseType, arg0);
        }
    }
}
